package constant

const (
	SCREEN_WIDTH  = 1280
	SCREEN_HEIGHT = 720

	ASTEROID_MIN_RADIUS = 20
	ASTEROID_KINDS      = 3
	ASTEROID_SPAWN_RATE = 0.8 // seconds
	ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

	PLAYER_MOVE_SPEED     float64 = 200
	PLAYER_ROTATION_SPEED float64 = 300
	PLAYER_RADUIS         int     = 20
	PLAYER_FIRE_RATE      string  = "0.1s" // seconds

	BULLET_SPEED  float64 = 400
	BULLET_RADIUS int     = 5
)
